//MAP
export const CURRENT_LOCATION = 'CURRENT_LOCATION'
export const REAL_ADDRESS = 'REAL_ADDRESS'

// USER DATA
export const SAVE_USER_DATA = 'SAVE_USER_DATA'
export const CHANGE_USER_DATA_PROPS = 'CHANGE_USER_DATA_PROPS'